version: '3.3' 
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db
  web:
    image: astrahov90/foodgram-project-react:latest
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine 

    ports:
      - "80:80"

    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - ./frontend/build:/usr/share/nginx/html/
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
      - ./docs/redoc.html:/usr/share/nginx/html/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/docs/openapi-schema.yml

    depends_on:
      - web
      - frontend

volumes:
  static_value:
  media_value: