# Generated by Django 2.2.16 on 2022-03-15 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20220315_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Содержит рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='fav_users', to='recipes.Recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(help_text='Содержит хозяина списка избранного', on_delete=django.db.models.deletion.CASCADE, related_name='fav_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин списка избранного')),
            ],
            options={
                'ordering': ['recipe'],
            },
        ),
    ]
