# Generated by Django 2.2.16 on 2022-03-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_shoplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientslist',
            name='amount',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredientslist',
            name='ingredient',
            field=models.ForeignKey(help_text='Содержит ингредиент', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='recipes.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientslist',
            name='recipe',
            field=models.ForeignKey(help_text='Содержит рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
    ]
