# Generated by Django 2.2.16 on 2022-03-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20220321_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'ordering': ['-recipe__created_date']},
        ),
        migrations.AlterModelOptions(
            name='shoplist',
            options={'ordering': ['-recipe__created_date']},
        ),
    ]
