# Generated by Django 2.2.16 on 2022-03-21 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220321_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientslist',
            name='amount',
            field=models.FloatField(help_text='Содержит количество ингредиентов', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления (мин)'),
        ),
    ]
