# Generated by Django 2.2.16 on 2022-03-22 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0014_auto_20220322_1005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourites',
            unique_together={('user', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='shoplist',
            unique_together={('user', 'recipe')},
        ),
    ]
