# Generated by Django 2.2.16 on 2022-03-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20220322_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsList',
            new_name='IngredientsRecipe',
        ),
    ]
