# Generated by Django 2.2.16 on 2022-03-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20220322_1112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shopcart',
            unique_together=set(),
        ),
    ]
