# Generated by Django 2.2.16 on 2022-03-15 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Неверное имя пользователя', regex='^[\\w.@+-]+')], verbose_name='Имя пользователя'),
        ),
    ]
